--- !ruby/object:Radiant::Config 
attributes: 
  id: "2"
  value: Publishing for Small Teams
  description: The tagline displayed underneath the main administration title
  key: admin.subtitle
attributes_cache: {}

