--- !ruby/object:Radiant::Config 
attributes: 
  id: "5"
  value: ""
  description: |
    Sets the text filter a new page has by default.  Valid options, in a vanilla Radiant install are:
    
    * _leave blank to set no default filter_
    * Markdown
    * SmartyPants
    * Textile

  key: defaults.page.filter
attributes_cache: {}

